### ISSUE TITLE
Prototype log upload script

### ISSUE THREAD

**Issue by griswaldbrooks** [kittcar/kitt_cloud#2]
Create first version of log uploader which can upload a tarred file to an aws bucket.

Requires:
- [x] @griswaldbrooks create logs.kittcar.com bucket on aws #3 
- [x] @griswaldbrooks add iam credentials #5 

Deliverables
- [x] In a package, one script which takes a file or directory and tars/zips it
- [x] Creates a bucket under logs.kittcar.com that is named by date
- [x] Uploads the tar to that bucket
- [ ] python unittest which tests the function calls

Follow up:
- [ ] Griz creates travis yaml to integrate test. #4
